Repository oqc-community/qat, pull requests merged in 2024-11, with the labels that each got.

#234 Temporary stop releases with version mismatch.
  .github/workflows/doc-publish.yml
  .github/workflows/package-publish.yml
Labels: devops, ignore-for-release

#206 Extending qiskit simulator capabilities
  src/qat/purr/backends/qiskit_simulator.py
  src/qat/purr/qatconfig.py
  tests/qat/test_qiskit_backend.py
Labels: bug, enhancement

#237 Resolve np.tanh warnings from soft square waveforms
  pyproject.toml
  src/qat/purr/backends/utilities.py
  tests/qat/test_utilities.py
Labels: bug

#217 [EXPERIMENTAL] Part 2: The new Control Flow infrastructure
  src/qat/backend/__init__.py
  src/qat/backend/analysis_passes.py
  src/qat/backend/codegen_base.py
  src/qat/backend/graph.py
  src/qat/backend/transform_passes.py
  src/qat/backend/validation_passes.py
  src/qat/purr/backends/qblox/constants.py
  src/qat/purr/compiler/instructions.py
  src/qat/utils/__init__.py
  src/qat/utils/algorithm.py
  tests/qat/backend/__init__.py
  tests/qat/backend/test_passes.py
  tests/qat/utils/builder_nuggets.py
Labels: enhancement, experimental

#232 Improved measurement instruction sequence
  src/qat/purr/compiler/builders.py
  src/qat/purr/compiler/instructions.py
  tests/qat/test_instructions.py
  tests/qat/test_qasm.py
  tests/qat/test_qat.py
  tests/qat/test_qir.py
  tests/qat/test_quantum_backend.py
Labels: enhancement

#239 Performance improvement: mid-circuit measurement validation
  src/qat/compiler/validation_passes.py
  src/qat/purr/backends/live.py
  tests/qat/test_quantum_backend.py
Labels: enhancement

#242 Cleanup sweep decomposition and test validity of the Sweep instruction
  src/qat/backend/transform_passes.py
  tests/qat/backend/test_passes.py
  tests/qat/test_instructions.py
Labels: bug

#240 [EXPERIMENTAL] Serialisation of QuantumHardwareModels
  poetry.lock
  pyproject.toml
  src/qat/model/autopopulate.py
  src/qat/model/component.py
  src/qat/model/device.py
  src/qat/model/hardware_model.py
  src/qat/model/serialisation.py
  src/qat/utils/pydantic.py
  tests/qat/model/test_serialisation.py
  tests/qat/model/test_serialisation_hardware_model.py
Labels: enhancement, experimental

#241 Minor performance improvement: get_X_from_Y
  src/qat/purr/compiler/builders.py
  src/qat/purr/compiler/execution.py
  src/qat/purr/compiler/hardware_models.py
  src/qat/purr/integrations/features.py
  src/qat/purr/integrations/qasm.py
Labels: enhancement

#184 Performance improvement: create_duration_timeline
  src/qat/purr/compiler/execution.py
  tests/qat/test_quantum_backend.py
Labels: enhancement

#229 Performance regression checks: benchmarking tests
  .github/workflows/package-build.yaml
  .gitignore
  README.rst
  poetry.lock
  pyproject.toml
  tests/benchmarking/__init__.py
  tests/benchmarking/qasm/10qb_ghz.qasm
  tests/benchmarking/qasm/10qb_random_cnot.qasm
  tests/benchmarking/qasm/2qb_clifford.qasm
  tests/benchmarking/qasm/2qb_random_cnot.qasm
  tests/benchmarking/qasm/bell_state.qasm
  tests/benchmarking/test_benchmarking.py
  tests/benchmarking/utils/models.py
Labels: enhancement

#219 [EXPERIMENTAL] Part 3: Faster Qblox integration
  src/qat/backend/analysis_passes.py
  src/qat/purr/backends/qblox/analysis_passes.py
  src/qat/purr/backends/qblox/codegen.py
  src/qat/purr/backends/qblox/constants.py
  src/qat/purr/backends/qblox/live.py
  tests/qat/backend/qblox/__init__.py
  tests/qat/backend/qblox/test_passes.py
  tests/qat/backend/test_passes.py
  tests/qat/qblox/test_codegen.py
  tests/qat/qblox/test_device.py
  tests/qat/qblox/test_live.py
  tests/qat/utils/builder_nuggets.py
Labels: enhancement, experimental

#247 Added error_mitigation as a property for QuantumExecutionEngine
  src/qat/purr/compiler/execution.py
  tests/qat/test_readout_mitigation.py
Labels: bug

#249 Fix broken Qasm3 gates.
  src/qat/purr/integrations/qasm.py
  tests/qat/qasm_utils.py
  tests/qat/test_qasm.py
Labels: bug

#252 Add support for patch releases
  .github/workflows/package-publish.yml
Labels: ignore-for-release

#253 Fix failing Qasm3 gates
  .github/workflows/package-build.yaml
  docs/source/conf.py
  pyproject.toml
  src/qat/purr/compiler/instructions.py
  src/qat/purr/integrations/qasm.py
  tests/qat/qasm_utils.py
  tests/qat/test_qasm.py
Labels: bug

#250 [EXPERIMENTAL] Fixes to Analysis and Codegen
  poetry.lock
  pyproject.toml
  src/qat/backend/analysis_passes.py
  src/qat/purr/backends/qblox/analysis_passes.py
  src/qat/purr/backends/qblox/codegen.py
  src/qat/purr/backends/qblox/live.py
  tests/qat/backend/qblox/test_passes.py
  tests/qat/backend/test_codegen.py
  tests/qat/backend/test_passes.py
  tests/qat/utils/builder_nuggets.py
Labels: backend, qblox

#256 [EXPERIMENTAL] Skeptical static `DeviceUpdate` instructions
  src/qat/backend/analysis_passes.py
  src/qat/purr/backends/qblox/analysis_passes.py
  src/qat/purr/backends/qblox/live.py
  tests/qat/backend/test_codegen.py
  tests/qat/backend/test_live.py
  tests/qat/utils/builder_nuggets.py
Labels: backend, qblox

#257 Patch modified gates with QASM2 implementations.
  docs/source/conf.py
  pyproject.toml
  src/qat/purr/integrations/grammars/stdgates.inc
  src/qat/purr/integrations/qasm.py
  tests/qat/files/qasm/instructions/CX.json
  tests/qat/files/qasm/instructions/c3sqrtx.json
  tests/qat/files/qasm/instructions/c3x.json
  tests/qat/files/qasm/instructions/c4x.json
  tests/qat/files/qasm/instructions/ccx.json
  tests/qat/files/qasm/instructions/ch.json
  tests/qat/files/qasm/instructions/cp.json
  tests/qat/files/qasm/instructions/cphase.json
  tests/qat/files/qasm/instructions/crx.json
  tests/qat/files/qasm/instructions/cry.json
  tests/qat/files/qasm/instructions/crz.json
  tests/qat/files/qasm/instructions/cswap.json
  tests/qat/files/qasm/instructions/csx.json
  tests/qat/files/qasm/instructions/cu.json
  tests/qat/files/qasm/instructions/cu1.json
  tests/qat/files/qasm/instructions/cu3.json
  tests/qat/files/qasm/instructions/cx.json
  tests/qat/files/qasm/instructions/cy.json
  tests/qat/files/qasm/instructions/cz.json
  tests/qat/files/qasm/instructions/ecr.json
  tests/qat/files/qasm/instructions/h.json
  tests/qat/files/qasm/instructions/id.json
  tests/qat/files/qasm/instructions/p.json
  tests/qat/files/qasm/instructions/phase.json
  tests/qat/files/qasm/instructions/rc3x.json
  tests/qat/files/qasm/instructions/rccx.json
  tests/qat/files/qasm/instructions/rx.json
  tests/qat/files/qasm/instructions/rxx.json
  tests/qat/files/qasm/instructions/ry.json
  tests/qat/files/qasm/instructions/rz.json
  tests/qat/files/qasm/instructions/rzz.json
  tests/qat/files/qasm/instructions/s.json
  tests/qat/files/qasm/instructions/sdg.json
  tests/qat/files/qasm/instructions/swap.json
  tests/qat/files/qasm/instructions/sx.json
  tests/qat/files/qasm/instructions/sxdg.json
  tests/qat/files/qasm/instructions/t.json
  tests/qat/files/qasm/instructions/tdg.json
  tests/qat/files/qasm/instructions/u.json
  tests/qat/files/qasm/instructions/u0.json
  tests/qat/files/qasm/instructions/u1.json
  tests/qat/files/qasm/instructions/u2.json
  tests/qat/files/qasm/instructions/u3.json
  tests/qat/files/qasm/instructions/x.json
  tests/qat/files/qasm/instructions/y.json
  tests/qat/files/qasm/instructions/z.json
  tests/qat/qasm_utils.py
  tests/qat/test_qasm.py
Labels: bug

#244 [EXPERIMENTAL] Builder for `QuantumHardwareModel`
  poetry.lock
  src/qat/model/autopopulate.py
  src/qat/model/builder.py
  src/qat/model/component.py
  src/qat/model/device.py
  src/qat/model/hardware_base.py
  src/qat/model/hardware_model.py
  src/qat/model/serialisation.py
  tests/qat/files/hardware/toshiko_lattice_connections.json
  tests/qat/model/__init__.py
  tests/qat/model/test_device.py
  tests/qat/model/test_hardware_model.py
  tests/qat/model/test_serialisation.py
  tests/qat/model/test_serialisation_hardware_model.py
Labels: enhancement, experimental

#261 Bug fix: resolve flaky sech waveform tests
  .github/workflows/package-build.yaml
  src/qat/purr/backends/utilities.py
Labels: bug

#258 Patch modified gates with QASM2 implementations.
  src/qat/purr/integrations/grammars/stdgates.inc
  src/qat/purr/integrations/qasm.py
  tests/qat/files/qasm/instructions/CX.json
  tests/qat/files/qasm/instructions/c3sqrtx.json
  tests/qat/files/qasm/instructions/c3x.json
  tests/qat/files/qasm/instructions/c4x.json
  tests/qat/files/qasm/instructions/ccx.json
  tests/qat/files/qasm/instructions/ch.json
  tests/qat/files/qasm/instructions/cp.json
  tests/qat/files/qasm/instructions/cphase.json
  tests/qat/files/qasm/instructions/crx.json
  tests/qat/files/qasm/instructions/cry.json
  tests/qat/files/qasm/instructions/crz.json
  tests/qat/files/qasm/instructions/cswap.json
  tests/qat/files/qasm/instructions/csx.json
  tests/qat/files/qasm/instructions/cu.json
  tests/qat/files/qasm/instructions/cu1.json
  tests/qat/files/qasm/instructions/cu3.json
  tests/qat/files/qasm/instructions/cx.json
  tests/qat/files/qasm/instructions/cy.json
  tests/qat/files/qasm/instructions/cz.json
  tests/qat/files/qasm/instructions/ecr.json
  tests/qat/files/qasm/instructions/h.json
  tests/qat/files/qasm/instructions/id.json
  tests/qat/files/qasm/instructions/p.json
  tests/qat/files/qasm/instructions/phase.json
  tests/qat/files/qasm/instructions/rc3x.json
  tests/qat/files/qasm/instructions/rccx.json
  tests/qat/files/qasm/instructions/rx.json
  tests/qat/files/qasm/instructions/rxx.json
  tests/qat/files/qasm/instructions/ry.json
  tests/qat/files/qasm/instructions/rz.json
  tests/qat/files/qasm/instructions/rzz.json
  tests/qat/files/qasm/instructions/s.json
  tests/qat/files/qasm/instructions/sdg.json
  tests/qat/files/qasm/instructions/swap.json
  tests/qat/files/qasm/instructions/sx.json
  tests/qat/files/qasm/instructions/sxdg.json
  tests/qat/files/qasm/instructions/t.json
  tests/qat/files/qasm/instructions/tdg.json
  tests/qat/files/qasm/instructions/u.json
  tests/qat/files/qasm/instructions/u0.json
  tests/qat/files/qasm/instructions/u1.json
  tests/qat/files/qasm/instructions/u2.json
  tests/qat/files/qasm/instructions/u3.json
  tests/qat/files/qasm/instructions/x.json
  tests/qat/files/qasm/instructions/y.json
  tests/qat/files/qasm/instructions/z.json
  tests/qat/qasm_utils.py
  tests/qat/test_qasm.py
Labels: bug

#259 Test coverage: gate decomposition tests
  src/qat/purr/compiler/builders.py
  tests/qat/test_gates.py
  tests/qat/utils/matrix_builder.py
Labels: bug, enhancement

#269 Ignore globalise phased X depreciation warning and update poetry lock
  poetry.lock
  pyproject.toml
Labels: ignore-for-release

#270 [EXPERIMENTAL] Raise a meaningful error when acquisition memory is exceeded
  src/qat/purr/backends/qblox/codegen.py
  src/qat/purr/backends/qblox/constants.py
  tests/qat/utils/builder_nuggets.py
Labels: backend, qblox

#272 Adjust passes to use QatIR.
  src/qat/backend/analysis_passes.py
  src/qat/backend/transform_passes.py
  src/qat/backend/validation_passes.py
  src/qat/compiler/transform_passes.py
  src/qat/compiler/validation_passes.py
  src/qat/core.py
  src/qat/ir/pass_base.py
  src/qat/purr/backends/qblox/analysis_passes.py
  src/qat/purr/backends/qblox/codegen.py
  src/qat/purr/backends/qblox/live.py
  src/qat/purr/compiler/runtime.py
  src/qat/runtime/analysis_passes.py
  tests/qat/backend/qblox/test_passes.py
  tests/qat/backend/test_codegen.py
  tests/qat/backend/test_passes.py
  tests/qat/ir/test_pass_infra.py
  tests/qat/runtime/test_runtime.py
Labels: experimental

#273 Bump to 2.5.0
  docs/source/conf.py
  poetry.lock
  pyproject.toml
Labels: ignore-for-release
