Repository oqc-community/qat, pull requests merged in 2024-10, with the labels that each got.

#213 Auto-generated release note categorisation based on github PR labels
  .github/release.yml
Labels: devops

#209 Bump to 2.2.0
  docs/source/conf.py
  poetry.lock
  pyproject.toml
Labels: ignore-for-release

#212 [BACKEND, QBLOX] Safely run control_hardware.set_data()
  src/qat/purr/backends/qblox/device.py
Labels: backend, qblox

#221 Make OpenPulseFeatures python 3.11+ compatible
  src/qat/purr/integrations/features.py
  tests/qat/test_integration_features.py
Labels: bug

#218 Consolidate support for "gaussian_square" waves
  src/qat/purr/backends/utilities.py
  src/qat/purr/integrations/qasm.py
  tests/qat/files/qasm/qasm3/waveform_tests/gaussian_square.qasm
  tests/qat/test_qasm.py
  tests/qat/test_utilities.py
Labels: bug, enhancement

#224 Re-enable json dumping and loading of instructions.
  src/qat/purr/utils/serializer.py
  tests/qat/test_instructions.py
Labels: bug

#223 Allow acquire time to be a Variable.
  src/qat/purr/compiler/builders.py
  src/qat/purr/compiler/instructions.py
  tests/qat/test_instructions.py
Labels: bug

#225 Devops/ker/formatting settings
  pyproject.toml
  tests/qat/ir/test_pass_infra.py
  tests/qat/qblox/test_codegen.py
  tests/qat/qblox/test_config.py
  tests/qat/qblox/test_live.py
  tests/qat/runtime/test_runtime.py
  tests/qat/test_compiler_config_dependency.py
  tests/qat/test_experimental_frontends.py
  tests/qat/test_instructions.py
  tests/qat/test_legacy_config.py
  tests/qat/test_qasm.py
  tests/qat/test_qat.py
  tests/qat/test_qir.py
  tests/qat/test_qiskit_backend.py
  tests/qat/test_quantum_backend.py
  tests/qat/test_readout_mitigation.py
  tests/qat/test_tket.py
  tests/qat/test_verification.py
Labels: devops

#214 Bugfix: capture in openpulse
  src/qat/purr/backends/live.py
  src/qat/purr/backends/qblox/live.py
  src/qat/purr/integrations/qasm.py
  tests/qat/files/qasm/qasm3/openpulse_tests/capture.qasm
  tests/qat/test_qasm.py
Labels: bug

#227 Bugfix: sech waveforms
  src/qat/purr/backends/utilities.py
  tests/qat/files/qasm/qasm3/waveform_tests/sech_waveform.qasm
  tests/qat/test_qasm.py
  tests/qat/test_utilities.py
Labels: bug

#228 bump to 2.3.0
  docs/source/conf.py
  pyproject.toml
Labels: ignore-for-release

#226 Improvement/ker/phase reset drop
  poetry.lock
  src/qat/purr/compiler/builders.py
  src/qat/purr/compiler/instructions.py
  tests/qat/test_instructions.py
  tests/qat/test_qasm.py
  tests/qat/test_qat.py
  tests/qat/test_qir.py
  tests/qat/test_quantum_backend.py
Labels: enhancement

#231 Revert "Improvement/ker/phase reset drop"
  src/qat/purr/compiler/builders.py
  src/qat/purr/compiler/instructions.py
  tests/qat/test_instructions.py
  tests/qat/test_qasm.py
  tests/qat/test_qat.py
  tests/qat/test_qir.py
  tests/qat/test_quantum_backend.py
Labels: ignore-for-release

#230 Remap measurements to multiple cregs in QiskitSim.
  src/qat/purr/backends/qiskit_simulator.py
  tests/qat/files/qasm/qasm2/split_measure_assign.qasm
  tests/qat/test_qiskit_backend.py
Labels: enhancement

#233 Bump version to 2.4.0 in prep for release.
  pyproject.toml
Labels: ignore-for-release
