Repository oqc-community/qat, pull requests merged in 2024-12, with the labels that each got.

#274 Bump version sigstore
  .github/workflows/package-publish.yml
Labels: bug, devops

#275 [Experimental] A/B pipeline tests.
  benchmarks/a-b_tests/__init__.py
  benchmarks/a-b_tests/test_pipeline.py
  benchmarks/conftest.py
  benchmarks/run.py
  benchmarks/utils/helpers.py
  pyproject.toml
Labels: experimental

#262 [EXPERIMENTAL] Finetune hardware model according to internal discussions.
  poetry.lock
  pyproject.toml
  src/qat/model/builder.py
  src/qat/model/convert_legacy.py
  src/qat/model/device.py
  src/qat/model/hardware_base.py
  src/qat/model/hardware_model.py
  tests/qat/model/test_device.py
  tests/qat/model/test_hardware_base.py
  tests/qat/model/test_hardware_model.py
  tests/qat/model/test_legacy_hardware_model.py
  tests/qat/utils/hardware_models.py
Labels: enhancement, experimental
